export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';
export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO';
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR';

export const OBTENER_PRODUCTO = 'OBTENER_PRODUCTO';
export const OBTENER_PRODUCTO_ERROR = 'OBTENER_PRODUCTO_ERROR';
export const OBTENER_PRODUCTO_EXITO = 'OBTENER_PRODUCTO_EXITO';

export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO';
export const ELIMINAR_PRODUCTO_EXITO = 'ELIMINAR_PRODUCTO_EXITO';
export const ELIMINAR_PRODUCTO_ERROR = 'ELIMINAR_PRODUCTO_ERROR';

export const EDITAR_PRODUCTO = 'EDITAR_PRODUCTO';
export const INICIAR_EDITAR_PRODUCTO = 'INICIAR_EDITAR_PRODUCTO';
export const EDITAR_PRODUCTO_EXITO = 'EDITAR_PRODUCTO_EXITO';
export const EDITAR_PRODUCTO_ERROR = 'EDITAR_PRODUCTO_ERROR';


export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';